name: ci

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Single deploy job since we're just deploying
  ci:
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["20.x"]
    
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install dependencies
        run: npm ci

      - name: Api build
        working-directory: ./api
        run: npm run build 
      
      - name: App build
        working-directory: ./app
        run: npm run build

      - name: App typecheck
        working-directory: ./app
        run: npm run check